CREATE DATABASE IF NOT EXISTS 'vinicius';

CREATE TABLE IF NOT EXISTS users (
  userId int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(20) NOT NULL,
  userPassword VARCHAR(40) NOT NULL
);

CREATE USER IF NOT EXISTS 'vinicius'@'localhost' IDENTIFIED BY '229149392119';

GRANT INSERT,SELECT ON `vinicius`.* TO 'vinicius'@'localhost';

FLUSH PRIVILEGES;